repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-json
      - id: end-of-file-fixer
      - id: name-tests-test
      - id: requirements-txt-fixer
      - id: trailing-whitespace  # Ensure the spelling is correct
        exclude: "log/.*|workspaces/.*" # logs file not include
