version: "3.8"

services:
  app:
    build: .
    container_name: Issue-Tracker-App
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - ENV=production
    depends_on:
      - pgdb
  pgdb:
    image: postgres:15
    container_name: Issue-Tracker
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=issue_tracker
    ports:
      - "5432:5432"
